[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"


[[redirects]]
  from = "https://portofolio-ion-varsescu.netlify.com/*"
  to = "https://portofolio.ionvarsescu.tk/:splat"
  status = 301
  force = true


